# ref: https://github.com/actions/runner-images
name: amd64 Windows Bazel

on: [push, pull_request, workflow_dispatch]

# Building using the github runner environement directly.
jobs:
  native:
    strategy:
      matrix:
        runner: [
          windows-2022,
          #windows-2019,
        ]
        bazel: [
          {compilation_mode: opt},
          {compilation_mode: dbg},
        ]
        cpp: [
          {version: 14, flags: "/std:c++14"},
          {version: 17, flags: "/std:c++17"},
          #{version: 20, flags: "/std:c++20"},
        ]
        python: [
          {version: '3.11'},
        ]
        exclude:
          - runner: windows-2019
            cpp: {version: 20}
          # only test -c dbg with VS 2022 version 17 to save compute time
          - runner: windows-2019
            bazel: {compilation_mode: dbg}
          - cpp: {version: 14}
            bazel: {compilation_mode: dbg}
          - cpp: {version: 20}
            bazel: {compilation_mode: dbg}
      fail-fast: false # Don't cancel all jobs if one fails.
    name: ${{ matrix.runner }}•Bazel(${{ matrix.bazel.compilation_mode }})•C++${{ matrix.cpp.version }}•Python${{ matrix.python.version }}
    runs-on: ${{ matrix.runner }}
    steps:
      - uses: actions/checkout@v5
      - name: Setup Python
        uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.python.version }}
      - name: Check Python
        run: |
          python --version
          python -m platform
      - name: Install Bazel
        run: choco install bazel
      - name: Check Bazel
        run: bazel version
      - name: Build
        run: >
          cd examples/basic &&
          bazel build
          -c ${{ matrix.bazel.compilation_mode }}
          --cxxopt=${{ matrix.cpp.flags }} --host_cxxopt=${{ matrix.cpp.flags }}
          --subcommands=pretty_print
          --enable_bzlmod
          //...
      - name: Test
        run: >
          cd examples/basic &&
          bazel test
          -c ${{ matrix.bazel.compilation_mode }}
          --cxxopt=${{ matrix.cpp.flags }} --host_cxxopt=${{ matrix.cpp.flags }}
          --subcommands=pretty_print
          --enable_bzlmod
          //...

  amd64_windows_bazel:
    runs-on: ubuntu-latest
    needs: native
    steps:
      - uses: actions/checkout@v5
